Name - Ankit
Roll No.-19MTS5630
Class-BSc Mathematical Science 2nd year(3rd sem)
Date-07 Sept 2020

In [ ]:
import numpy as np

1. Create a random array of 15 positive elements and perform the following operations with the help of Ufuncs.

In [ ]:
data = np.random.rand(15)
data

array([0.60337529, 0.12961288, 0.65804744, 0.44766592, 0.08327683,
       0.62714535, 0.42972574, 0.05816392, 0.49236449, 0.36605242,
       0.11435455, 0.26892984, 0.1853887 , 0.22654384, 0.57372847])

(a) Square Root

In [ ]:
np.sqrt(data)

array([0.77677235, 0.3600179 , 0.81120124, 0.66907841, 0.28857725,
       0.79192509, 0.6555347 , 0.24117196, 0.70168689, 0.60502266,
       0.3381635 , 0.51858446, 0.43056788, 0.47596622, 0.75744866])

(b) Exponent

In [ ]:
np.exp(data)

array([1.82827937, 1.13838761, 1.93101823, 1.56465589, 1.08684263,
       1.87225831, 1.53683598, 1.05988871, 1.63618038, 1.44203083,
       1.12114956, 1.30856333, 1.20368622, 1.2542576 , 1.77487229])

(c) Square

In [ ]:
np.square(data)

array([0.36406174, 0.0167995 , 0.43302644, 0.20040478, 0.00693503,
       0.39331129, 0.18466421, 0.00338304, 0.24242279, 0.13399437,
       0.01307696, 0.07232326, 0.03436897, 0.05132211, 0.32916436])

(d) Log (base: 10, e, 2)

In [ ]:
#log 10
np.log10(data)

array([-0.21941248, -0.88735182, -0.18174279, -0.34904596, -1.07947583,
       -0.20263179, -0.36680863, -1.23534636, -0.30771328, -0.43645672,
       -0.94174654, -0.57036101, -0.73191675, -0.64484774, -0.2412936 ])

In [ ]:
#log 2
np.log2(data)

array([-0.72887248, -2.94771895, -0.60373649, -1.15950559, -3.58594109,
       -0.67312824, -1.21851189, -4.10373178, -1.02220138, -1.44987785,
       -3.12841429, -1.89469826, -2.43137482, -2.14213783, -0.80155998])

In [ ]:
#log e
np.log(data)

array([[ 1.19890922,  2.4890984 ,  2.69315075,  3.70210433,  3.95737817,
         3.96445551,  4.00382209,  4.10771618,  4.16526054,  4.59787393],
       [ 0.6046177 ,  1.71110386,  2.24239011,  3.19361701,  3.67789606,
         3.87358515,  4.34279222,  4.34324   ,  4.50162692,  4.59908288],
       [ 0.54133902,  1.73504628,  2.65065073,  2.94504118,  3.03024041,
         4.03803727,  4.12379463,  4.32511443,  4.38799028,  4.43523492],
       [ 1.59875877,  3.22697821,  3.29280911,  3.85015634,  3.9856875 ,
         4.06793783,  4.21223589,  4.29859519,  4.41683925,  4.59401202],
       [ 3.00516454,  3.43070794,  4.04624924,  4.19304801,  4.30119324,
         4.39785069,  4.50285407,  4.53560444,  4.58325696,  4.59772683],
       [ 0.50842891,  2.57510475,  3.53289608,  3.66302927,  3.77437833,
         4.17923849,  4.18271839,  4.26229914,  4.27854029,  4.3717317 ],
       [ 1.21141803,  1.48775066,  2.5261498 ,  3.34703118,  3.43957843,
         3.71169125,  3.7155305 ,  3.83022246

(e) Ceiling

In [ ]:
np.ceil(data)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(f) Floor

In [ ]:
np.floor(data)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(g) Near round integer

In [ ]:
np.rint(data)

array([1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

(h) Check if a value is NAN, Infinite or Finite

In [ ]:
#checking for nan values
np.isnan(data)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
#checking finite and infinite values
np.isfinite(data)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
np.isinf(data)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

(i) Trigo operations - sin, cos, tan

In [ ]:
#trigonometric functions - cos,sin,tan
np.cos(data)

array([0.82342508, 0.991612  , 0.79118787, 0.90145989, 0.99653449,
       0.80970601, 0.90908005, 0.99830896, 0.8812176 , 0.93374758,
       0.99346864, 0.96405579, 0.98286468, 0.9744485 , 0.83988313])

In [ ]:
np.sin(data)

array([0.567425  , 0.12925028, 0.61157318, 0.43286264, 0.08318061,
       0.58683573, 0.4166215 , 0.05813113, 0.47271084, 0.35793218,
       0.11410548, 0.26569989, 0.18432858, 0.22461102, 0.54276729])

In [ ]:
np.tan(data)

array([0.68910337, 0.13034361, 0.77298099, 0.48017959, 0.08346987,
       0.7247516 , 0.45828912, 0.0582296 , 0.53642918, 0.38332863,
       0.11485564, 0.27560635, 0.18754218, 0.23050066, 0.64624146])

2. Create two random 2-D arrays of size 5 rows and 4 columns each and perform the following operations in an element-wise manner using inbuilt binary functions from Numpy.

In [ ]:
arr2d1=np.random.rand(5,4)
arr2d2=np.random.rand(5,4)

In [ ]:
arr2d1

array([[0.00431743, 0.99028439, 0.74026981, 0.59505991],
       [0.64003161, 0.03142869, 0.46875672, 0.40230156],
       [0.08055767, 0.32873847, 0.32345652, 0.19344651],
       [0.46612714, 0.10441358, 0.48584058, 0.31871977],
       [0.80631466, 0.24017855, 0.88911777, 0.57348054]])

In [ ]:
arr2d2

array([[0.0043784 , 0.26866407, 0.05700771, 0.72006424],
       [0.95532917, 0.357385  , 0.93333562, 0.93000566],
       [0.4746608 , 0.71428429, 0.09460127, 0.68458376],
       [0.32427462, 0.95030086, 0.6507672 , 0.45676022],
       [0.42488453, 0.01514081, 0.66425242, 0.85351326]])

(a) Addition

In [ ]:
np.add(arr2d1,arr2d2)

array([[0.00869583, 1.25894846, 0.79727752, 1.31512415],
       [1.59536078, 0.38881369, 1.40209234, 1.33230723],
       [0.55521847, 1.04302276, 0.41805779, 0.87803028],
       [0.79040176, 1.05471443, 1.13660778, 0.77547999],
       [1.23119919, 0.25531936, 1.55337018, 1.4269938 ]])

(b) Multiplication

In [ ]:
np.multiply(arr2d1, arr2d2)

array([[1.89034368e-05, 2.66053839e-01, 4.22010853e-02, 4.28481361e-01],
       [6.11440865e-01, 1.12321426e-02, 4.37507345e-01, 3.74142734e-01],
       [3.82375687e-02, 2.34812726e-01, 3.05993964e-02, 1.32430342e-01],
       [1.51153202e-01, 9.92243108e-02, 3.16169116e-01, 1.45578513e-01],
       [3.42590623e-01, 3.63649802e-03, 5.90598626e-01, 4.89473247e-01]])

(c) Division

In [ ]:
np.divide(arr2d1, arr2d2)

array([[ 0.98607493,  3.68595762, 12.98543373,  0.82639836],
       [ 0.66995925,  0.08794071,  0.50223811,  0.43257969],
       [ 0.16971629,  0.46023478,  3.41915637,  0.28257538],
       [ 1.43744564,  0.10987423,  0.74656588,  0.69778354],
       [ 1.89772659, 15.8629912 ,  1.33852394,  0.67190584]])

(d) Subtraction

In [ ]:
np.subtract(arr2d1,arr2d2)

array([[-6.09695150e-05,  7.21620317e-01,  6.83262105e-01,
        -1.25004334e-01],
       [-3.15297557e-01, -3.25956313e-01, -4.64578899e-01,
        -5.27704100e-01],
       [-3.94103132e-01, -3.85545811e-01,  2.28855255e-01,
        -4.91137246e-01],
       [ 1.41852519e-01, -8.45887280e-01, -1.64926614e-01,
        -1.38040457e-01],
       [ 3.81430136e-01,  2.25037740e-01,  2.24865348e-01,
        -2.80032713e-01]])

(e) Power

In [ ]:
np.power(arr2d1, arr2d2)

array([[0.97644114, 0.99738044, 0.9830016 , 0.68812798],
       [0.65291789, 0.29038017, 0.49304163, 0.42877639],
       [0.30253235, 0.4517456 , 0.89872736, 0.32478143],
       [0.78073633, 0.1168218 , 0.62514454, 0.593167  ],
       [0.91258901, 0.97863509, 0.92490278, 0.62214627]])

(f) Maximum & Minimum of two arrays

In [ ]:
#maximum
np.maximum(arr2d1, arr2d2)

array([[0.0043784 , 0.99028439, 0.74026981, 0.72006424],
       [0.95532917, 0.357385  , 0.93333562, 0.93000566],
       [0.4746608 , 0.71428429, 0.32345652, 0.68458376],
       [0.46612714, 0.95030086, 0.6507672 , 0.45676022],
       [0.80631466, 0.24017855, 0.88911777, 0.85351326]])

In [ ]:
#minimum
np.minimum(arr2d1, arr2d2)

array([[0.00431743, 0.26866407, 0.05700771, 0.59505991],
       [0.64003161, 0.03142869, 0.46875672, 0.40230156],
       [0.08055767, 0.32873847, 0.09460127, 0.19344651],
       [0.32427462, 0.10441358, 0.48584058, 0.31871977],
       [0.42488453, 0.01514081, 0.66425242, 0.57348054]])

(g) Mod of two arrays

In [ ]:
np.mod(arr2d1, arr2d2)

array([[0.00431743, 0.18429217, 0.05617732, 0.59505991],
       [0.64003161, 0.03142869, 0.46875672, 0.40230156],
       [0.08055767, 0.32873847, 0.03965272, 0.19344651],
       [0.14185252, 0.10441358, 0.48584058, 0.31871977],
       [0.38143014, 0.01306639, 0.22486535, 0.57348054]])

(h) Copy the sign of one array to another

In [ ]:
np.copysign(arr2d1, arr2d2)

array([[0.00431743, 0.99028439, 0.74026981, 0.59505991],
       [0.64003161, 0.03142869, 0.46875672, 0.40230156],
       [0.08055767, 0.32873847, 0.32345652, 0.19344651],
       [0.46612714, 0.10441358, 0.48584058, 0.31871977],
       [0.80631466, 0.24017855, 0.88911777, 0.57348054]])

(i) Compare elements: >, >=, ==, <=, <

In [ ]:
#greater
np.greater(arr2d1, arr2d2)

array([[False,  True,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [ ]:
#greater or equal
np.greater_equal(arr2d1, arr2d2)

array([[False,  True,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [ ]:
#less
np.less(arr2d1, arr2d2)

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [ ]:
#less or equal
np.less_equal(arr2d1, arr2d2)

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [ ]:
#equal
np.equal(arr2d1, arr2d2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

(j) Logical Operations: AND, OR, XOR

In [ ]:
#logical and
np.logical_and(arr2d1, arr2d2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#logical or
np.logical_or(arr2d1, arr2d2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#logical xor
np.logical_xor(arr2d1, arr2d2)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

3. Create an array of size 30x10 having random elements in the range -100 to 100. Perform the following operations on the array.

In [ ]:
arr1=np.random.rand(300).reshape((30,10))
arr1

array([[0.52691571, 0.03316497, 0.40532508, 0.99273029, 0.60807685,
        0.54807228, 0.64409461, 0.52319972, 0.12050407, 0.14778165],
       [0.24376438, 0.39563068, 0.99393118, 0.90163701, 0.76922023,
        0.01830552, 0.05535068, 0.76956475, 0.48114575, 0.09415809],
       [0.56714918, 0.20702209, 0.84371943, 0.0566919 , 0.80478517,
        0.01718306, 0.19011445, 0.14163252, 0.7557416 , 0.61793281],
       [0.82834054, 0.58436332, 0.25203382, 0.53822279, 0.98890385,
        0.47000411, 0.73596332, 0.6750731 , 0.26918374, 0.04946888],
       [0.99258427, 0.73787788, 0.20189538, 0.9327988 , 0.97832513,
        0.30898509, 0.81275994, 0.90274413, 0.57182576, 0.66224336],
       [0.38979243, 0.65316095, 0.70972973, 0.43570413, 0.72135067,
        0.65543785, 0.13132693, 0.79180631, 0.34222937, 0.01662677],
       [0.41080374, 0.31173813, 0.2841824 , 0.03358243, 0.46072786,
        0.12505266, 0.95749508, 0.60088742, 0.04427126, 0.40922959],
       [0.49119971, 0.48896546, 0.1727702

In [ ]:
data=arr1*100
data

array([[52.69157148,  3.31649736, 40.5325083 , 99.27302922, 60.80768497,
        54.80722824, 64.40946138, 52.31997204, 12.05040658, 14.77816493],
       [24.37643808, 39.56306832, 99.39311811, 90.16370074, 76.92202275,
         1.83055225,  5.53506805, 76.95647512, 48.11457524,  9.41580922],
       [56.71491759, 20.70220891, 84.3719429 ,  5.66919016, 80.4785167 ,
         1.71830616, 19.01144527, 14.1632521 , 75.57416021, 61.79328075],
       [82.83405371, 58.43633232, 25.20338249, 53.8222794 , 98.89038518,
        47.00041065, 73.59633235, 67.50730998, 26.91837427,  4.94688841],
       [99.25842738, 73.78778806, 20.1895379 , 93.27988029, 97.83251275,
        30.89850944, 81.27599352, 90.27441343, 57.18257626, 66.22433611],
       [38.97924279, 65.31609539, 70.97297293, 43.57041348, 72.13506697,
        65.54378468, 13.13269277, 79.18063051, 34.2229366 ,  1.66267693],
       [41.08037445, 31.17381332, 28.41823955,  3.35824338, 46.07278638,
        12.50526558, 95.74950752, 60.08874153

In [ ]:
arr2d = np.arange(-100,100,0.67).reshape((30, 10))
arr2d

ValueError: ignored

(a) Sum of the array

In [ ]:
data.sum()

14409.739701455306

In [ ]:
#using np function
np.sum(data)

14409.739701455303

(b) Mean of the array

In [ ]:
data.mean()


48.032465671517684

In [ ]:
#using np function
np.mean(data)

48.032465671517684

(c) Standard Deviation of the array

In [ ]:
data.std()

29.711491354628745

In [ ]:
#using np function
np.std(data)

29.711491354628745

(d) Variance of the array

In [ ]:

data.var()

882.7727185161787

In [ ]:
#using np function
np.var(data)

882.7727185161787

(e) Cumulative Sum for each column

In [ ]:
data.cumsum(axis=0)

array([[  52.69157148,    3.31649736,   40.5325083 ,   99.27302922,
          60.80768497,   54.80722824,   64.40946138,   52.31997204,
          12.05040658,   14.77816493],
       [  77.06800956,   42.87956569,  139.92562641,  189.43672996,
         137.72970772,   56.63778049,   69.94452943,  129.27644715,
          60.16498182,   24.19397416],
       [ 133.78292715,   63.5817746 ,  224.29756931,  195.10592012,
         218.20822442,   58.35608665,   88.9559747 ,  143.43969925,
         135.73914202,   85.98725491],
       [ 216.61698086,  122.01810692,  249.50095179,  248.92819952,
         317.09860961,  105.3564973 ,  162.55230705,  210.94700923,
         162.65751629,   90.93414332],
       [ 315.87540824,  195.80589498,  269.69048969,  342.20807982,
         414.93112235,  136.25500674,  243.82830057,  301.22142266,
         219.84009255,  157.15847943],
       [ 354.85465103,  261.12199038,  340.66346262,  385.77849329,
         487.06618932,  201.79879142,  256.96099334,  380

In [ ]:
#using np function
np.cumsum(data,axis=0)

array([[  52.69157148,    3.31649736,   40.5325083 ,   99.27302922,
          60.80768497,   54.80722824,   64.40946138,   52.31997204,
          12.05040658,   14.77816493],
       [  77.06800956,   42.87956569,  139.92562641,  189.43672996,
         137.72970772,   56.63778049,   69.94452943,  129.27644715,
          60.16498182,   24.19397416],
       [ 133.78292715,   63.5817746 ,  224.29756931,  195.10592012,
         218.20822442,   58.35608665,   88.9559747 ,  143.43969925,
         135.73914202,   85.98725491],
       [ 216.61698086,  122.01810692,  249.50095179,  248.92819952,
         317.09860961,  105.3564973 ,  162.55230705,  210.94700923,
         162.65751629,   90.93414332],
       [ 315.87540824,  195.80589498,  269.69048969,  342.20807982,
         414.93112235,  136.25500674,  243.82830057,  301.22142266,
         219.84009255,  157.15847943],
       [ 354.85465103,  261.12199038,  340.66346262,  385.77849329,
         487.06618932,  201.79879142,  256.96099334,  380

(f) Cumulative Sum for each row

In [ ]:
data.cumsum(axis=1)

array([[ 52.69157148,  56.00806885,  96.54057715, 195.81360637,
        256.62129135, 311.42851958, 375.83798096, 428.157953  ,
        440.20835958, 454.98652451],
       [ 24.37643808,  63.9395064 , 163.3326245 , 253.49632524,
        330.41834799, 332.24890025, 337.7839683 , 414.74044341,
        462.85501865, 472.27082788],
       [ 56.71491759,  77.4171265 , 161.7890694 , 167.45825956,
        247.93677625, 249.65508242, 268.66652769, 282.82977979,
        358.40393999, 420.19722075],
       [ 82.83405371, 141.27038604, 166.47376852, 220.29604792,
        319.18643311, 366.18684376, 439.7831761 , 507.29048608,
        534.20886035, 539.15574876],
       [ 99.25842738, 173.04621545, 193.23575334, 286.51563364,
        384.34814638, 415.24665582, 496.52264935, 586.79706278,
        643.97963904, 710.20397514],
       [ 38.97924279, 104.29533818, 175.26831112, 218.83872459,
        290.97379156, 356.51757624, 369.65026901, 448.83089952,
        483.05383612, 484.71651306],
       [ 4

In [ ]:
#using np function
np.cumsum(data,axis=1)

array([[ 52.69157148,  56.00806885,  96.54057715, 195.81360637,
        256.62129135, 311.42851958, 375.83798096, 428.157953  ,
        440.20835958, 454.98652451],
       [ 24.37643808,  63.9395064 , 163.3326245 , 253.49632524,
        330.41834799, 332.24890025, 337.7839683 , 414.74044341,
        462.85501865, 472.27082788],
       [ 56.71491759,  77.4171265 , 161.7890694 , 167.45825956,
        247.93677625, 249.65508242, 268.66652769, 282.82977979,
        358.40393999, 420.19722075],
       [ 82.83405371, 141.27038604, 166.47376852, 220.29604792,
        319.18643311, 366.18684376, 439.7831761 , 507.29048608,
        534.20886035, 539.15574876],
       [ 99.25842738, 173.04621545, 193.23575334, 286.51563364,
        384.34814638, 415.24665582, 496.52264935, 586.79706278,
        643.97963904, 710.20397514],
       [ 38.97924279, 104.29533818, 175.26831112, 218.83872459,
        290.97379156, 356.51757624, 369.65026901, 448.83089952,
        483.05383612, 484.71651306],
       [ 4

(g) Cumulative Product for each column

In [ ]:
data.cumprod(axis=0)

array([[5.26915715e+01, 3.31649736e+00, 4.05325083e+01, 9.92730292e+01,
        6.08076850e+01, 5.48072282e+01, 6.44094614e+01, 5.23199720e+01,
        1.20504066e+01, 1.47781649e+01],
       [1.28443283e+03, 1.31210812e+02, 4.02865238e+03, 8.95082370e+03,
        4.67745013e+03, 1.00327495e+02, 3.56510752e+02, 4.02636063e+03,
        5.79800194e+02, 1.39148382e+02],
       [7.28465021e+04, 2.71635364e+03, 3.39905229e+05, 5.07439216e+04,
        3.76434248e+05, 1.72393353e+02, 6.77778464e+03, 5.70263606e+04,
        4.38179127e+04, 8.59843502e+03],
       [6.03417106e+06, 1.58733744e+05, 8.56676149e+06, 2.73115353e+06,
        3.72257278e+07, 8.10255839e+03, 4.98820091e+05, 3.84969620e+06,
        1.17950697e+06, 4.25354985e+04],
       [5.98942330e+08, 1.17126119e+07, 1.72958956e+08, 2.54761674e+08,
        3.64188649e+09, 2.50356977e+05, 4.05420985e+07, 3.47529066e+08,
        6.74472475e+07, 2.81688515e+06],
       [2.33463185e+10, 7.65022073e+08, 1.22754113e+10, 1.11000715e+10,
   

In [ ]:
#using np function
np.cumprod(data,axis=0)

array([[5.26915715e+01, 3.31649736e+00, 4.05325083e+01, 9.92730292e+01,
        6.08076850e+01, 5.48072282e+01, 6.44094614e+01, 5.23199720e+01,
        1.20504066e+01, 1.47781649e+01],
       [1.28443283e+03, 1.31210812e+02, 4.02865238e+03, 8.95082370e+03,
        4.67745013e+03, 1.00327495e+02, 3.56510752e+02, 4.02636063e+03,
        5.79800194e+02, 1.39148382e+02],
       [7.28465021e+04, 2.71635364e+03, 3.39905229e+05, 5.07439216e+04,
        3.76434248e+05, 1.72393353e+02, 6.77778464e+03, 5.70263606e+04,
        4.38179127e+04, 8.59843502e+03],
       [6.03417106e+06, 1.58733744e+05, 8.56676149e+06, 2.73115353e+06,
        3.72257278e+07, 8.10255839e+03, 4.98820091e+05, 3.84969620e+06,
        1.17950697e+06, 4.25354985e+04],
       [5.98942330e+08, 1.17126119e+07, 1.72958956e+08, 2.54761674e+08,
        3.64188649e+09, 2.50356977e+05, 4.05420985e+07, 3.47529066e+08,
        6.74472475e+07, 2.81688515e+06],
       [2.33463185e+10, 7.65022073e+08, 1.22754113e+10, 1.11000715e+10,
   

(h) Cumulative Product for each row

In [ ]:
data.cumprod(axis=1)

array([[5.26915715e+01, 1.74751458e+02, 7.08311492e+03, 7.03162274e+05,
        4.27576701e+07, 2.34342938e+09, 1.50939024e+11, 7.89712553e+12,
        9.51635734e+13, 1.40634298e+15],
       [2.43764381e+01, 9.64406685e+02, 9.58553875e+04, 8.64267648e+06,
        6.64812157e+08, 1.21697339e+09, 6.73603054e+09, 5.18381166e+11,
        2.49416896e+13, 2.34846191e+14],
       [5.67149176e+01, 1.17412407e+03, 9.90631292e+04, 5.61607717e+05,
        4.51973560e+07, 7.76628954e+07, 1.47648389e+09, 2.09118135e+10,
        1.58039274e+12, 9.76576525e+13],
       [8.28340537e+01, 4.84051829e+03, 1.21997434e+05, 6.56617997e+06,
        6.49332067e+08, 3.05188738e+10, 2.24607718e+12, 1.51626628e+14,
        4.08154233e+15, 2.01909344e+16],
       [9.92584274e+01, 7.32405980e+03, 1.47869383e+05, 1.37932383e+07,
        1.34942717e+09, 4.16952880e+10, 3.38882596e+12, 3.05924276e+14,
        1.74935382e+16, 1.15849796e+18],
       [3.89792428e+01, 2.54597194e+03, 1.80695198e+05, 7.87296447e+06,
   

In [ ]:
#using np function
np.cumprod(data,axis=1)

array([[5.26915715e+01, 1.74751458e+02, 7.08311492e+03, 7.03162274e+05,
        4.27576701e+07, 2.34342938e+09, 1.50939024e+11, 7.89712553e+12,
        9.51635734e+13, 1.40634298e+15],
       [2.43764381e+01, 9.64406685e+02, 9.58553875e+04, 8.64267648e+06,
        6.64812157e+08, 1.21697339e+09, 6.73603054e+09, 5.18381166e+11,
        2.49416896e+13, 2.34846191e+14],
       [5.67149176e+01, 1.17412407e+03, 9.90631292e+04, 5.61607717e+05,
        4.51973560e+07, 7.76628954e+07, 1.47648389e+09, 2.09118135e+10,
        1.58039274e+12, 9.76576525e+13],
       [8.28340537e+01, 4.84051829e+03, 1.21997434e+05, 6.56617997e+06,
        6.49332067e+08, 3.05188738e+10, 2.24607718e+12, 1.51626628e+14,
        4.08154233e+15, 2.01909344e+16],
       [9.92584274e+01, 7.32405980e+03, 1.47869383e+05, 1.37932383e+07,
        1.34942717e+09, 4.16952880e+10, 3.38882596e+12, 3.05924276e+14,
        1.74935382e+16, 1.15849796e+18],
       [3.89792428e+01, 2.54597194e+03, 1.80695198e+05, 7.87296447e+06,
   

(i) Sort the array

In [ ]:
data.sort()
data

array([[ 3.31649736, 12.05040658, 14.77816493, 40.5325083 , 52.31997204,
        52.69157148, 54.80722824, 60.80768497, 64.40946138, 99.27302922],
       [ 1.83055225,  5.53506805,  9.41580922, 24.37643808, 39.56306832,
        48.11457524, 76.92202275, 76.95647512, 90.16370074, 99.39311811],
       [ 1.71830616,  5.66919016, 14.1632521 , 19.01144527, 20.70220891,
        56.71491759, 61.79328075, 75.57416021, 80.4785167 , 84.3719429 ],
       [ 4.94688841, 25.20338249, 26.91837427, 47.00041065, 53.8222794 ,
        58.43633232, 67.50730998, 73.59633235, 82.83405371, 98.89038518],
       [20.1895379 , 30.89850944, 57.18257626, 66.22433611, 73.78778806,
        81.27599352, 90.27441343, 93.27988029, 97.83251275, 99.25842738],
       [ 1.66267693, 13.13269277, 34.2229366 , 38.97924279, 43.57041348,
        65.31609539, 65.54378468, 70.97297293, 72.13506697, 79.18063051],
       [ 3.35824338,  4.42712619, 12.50526558, 28.41823955, 31.17381332,
        40.92295914, 41.08037445, 46.07278638

In [ ]:
#using np function
np.sort(data)

array([[ 3.31649736, 12.05040658, 14.77816493, 40.5325083 , 52.31997204,
        52.69157148, 54.80722824, 60.80768497, 64.40946138, 99.27302922],
       [ 1.83055225,  5.53506805,  9.41580922, 24.37643808, 39.56306832,
        48.11457524, 76.92202275, 76.95647512, 90.16370074, 99.39311811],
       [ 1.71830616,  5.66919016, 14.1632521 , 19.01144527, 20.70220891,
        56.71491759, 61.79328075, 75.57416021, 80.4785167 , 84.3719429 ],
       [ 4.94688841, 25.20338249, 26.91837427, 47.00041065, 53.8222794 ,
        58.43633232, 67.50730998, 73.59633235, 82.83405371, 98.89038518],
       [20.1895379 , 30.89850944, 57.18257626, 66.22433611, 73.78778806,
        81.27599352, 90.27441343, 93.27988029, 97.83251275, 99.25842738],
       [ 1.66267693, 13.13269277, 34.2229366 , 38.97924279, 43.57041348,
        65.31609539, 65.54378468, 70.97297293, 72.13506697, 79.18063051],
       [ 3.35824338,  4.42712619, 12.50526558, 28.41823955, 31.17381332,
        40.92295914, 41.08037445, 46.07278638