Name - Ankit
Roll No.-19MTS5630
Class-BSc Mathematical Science 2nd year(3rd sem)
Date-07 Sept 2020


In [ ]:
import numpy as np


 Create a 2-D Array of 8 rows and 10 columns with random elements and perform the following operations on them



In [ ]:
data=np.random.rand(8,10)
data

array([[0.57941979, 0.37012872, 0.1487552 , 0.85850761, 0.45700639,
        0.63736474, 0.01272707, 0.80074665, 0.79472084, 0.87794459],
       [0.23382876, 0.27441256, 0.95484165, 0.14495023, 0.04501631,
        0.17308561, 0.48651201, 0.36106834, 0.34325504, 0.15770137],
       [0.62099816, 0.31939085, 0.71113366, 0.86315745, 0.16269482,
        0.97056755, 0.23351128, 0.56505401, 0.28266941, 0.69254359],
       [0.67688869, 0.94380298, 0.28985208, 0.54235758, 0.68843525,
        0.42260737, 0.23122637, 0.12373243, 0.83557507, 0.41795576],
       [0.86218835, 0.32817241, 0.04392135, 0.85937168, 0.79683251,
        0.20709436, 0.35913089, 0.03726253, 0.15741166, 0.44873446],
       [0.01567637, 0.78223999, 0.7372134 , 0.42070561, 0.83132605,
        0.68195522, 0.78638214, 0.50257716, 0.97974516, 0.62922859],
       [0.99189509, 0.82747082, 0.90554211, 0.14351788, 0.01500922,
        0.4243087 , 0.5375096 , 0.45819655, 0.13186782, 0.68652328],
       [0.88904049, 0.31599528, 0.9869347

(a) Check the data type, shape and dimension of the created array

In [ ]:
#the data type of the elements of the array
data.dtype

dtype('float64')

In [ ]:
#the dimension of the array
data.shape

(8, 10)

In [ ]:
#the dimension of the array
data.ndim

2

(b) Perform addition & subtraction with itself


In [ ]:
#Addition
data+data

array([[1.15883958, 0.74025745, 0.29751041, 1.71701521, 0.91401278,
        1.27472948, 0.02545414, 1.6014933 , 1.58944168, 1.75588917],
       [0.46765751, 0.54882512, 1.9096833 , 0.28990046, 0.09003263,
        0.34617122, 0.97302403, 0.72213668, 0.68651007, 0.31540274],
       [1.24199631, 0.6387817 , 1.42226732, 1.7263149 , 0.32538964,
        1.94113509, 0.46702255, 1.13010803, 0.56533882, 1.38508718],
       [1.35377739, 1.88760597, 0.57970415, 1.08471515, 1.37687051,
        0.84521474, 0.46245275, 0.24746486, 1.67115014, 0.83591151],
       [1.7243767 , 0.65634482, 0.08784271, 1.71874336, 1.59366502,
        0.41418872, 0.71826178, 0.07452505, 0.31482332, 0.89746892],
       [0.03135274, 1.56447998, 1.47442679, 0.84141123, 1.6626521 ,
        1.36391043, 1.57276428, 1.00515432, 1.95949032, 1.25845718],
       [1.98379019, 1.65494165, 1.81108422, 0.28703576, 0.03001844,
        0.84861739, 1.0750192 , 0.91639311, 0.26373565, 1.37304657],
       [1.77808097, 0.63199057, 1.9738694

In [ ]:
#subtraction
data-data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

(c) Multiply all the elements by 90


In [ ]:
#Multiplication by 90
data*90

array([[52.14778122, 33.31158505, 13.3879683 , 77.26568459, 41.13057527,
        57.36282657,  1.14543651, 72.06719859, 71.52487581, 79.01501279],
       [21.04458803, 24.69713019, 85.93574871, 13.04552077,  4.05146829,
        15.57770503, 43.78608126, 32.49615059, 30.89295331, 14.19312327],
       [55.88983403, 28.74517663, 64.00202924, 77.6841704 , 14.64253377,
        87.35107919, 21.01601486, 50.85486131, 25.44024689, 62.3289229 ],
       [60.9199825 , 84.94226857, 26.08668696, 48.81218178, 61.95917283,
        38.03466339, 20.81037356, 11.13591851, 75.20175617, 37.61601814],
       [77.59695137, 29.5355168 ,  3.95292187, 77.34345129, 71.71492612,
        18.63849227, 32.32178018,  3.35362726, 14.16704937, 40.38610132],
       [ 1.41087326, 70.4015993 , 66.34920559, 37.86350533, 74.81934433,
        61.37596957, 70.77439238, 45.23194455, 88.17706448, 56.63057311],
       [89.27055852, 74.47237411, 81.49878971, 12.91660937,  1.35082965,
        38.18778256, 48.37586384, 41.23768991

(d) Divide all the elements by 0.05


In [ ]:
#divsion by 0.05
data/0.05

array([[11.58839583,  7.40257446,  2.97510407, 17.17015213,  9.14012784,
        12.74729479,  0.25454145, 16.01493302, 15.89441685, 17.55889173],
       [ 4.67657512,  5.48825115, 19.09683305,  2.89900462,  0.90032629,
         3.46171223,  9.73024028,  7.2213668 ,  6.86510074,  3.15402739],
       [12.41996312,  6.38781703, 14.22267316, 17.26314898,  3.25389639,
        19.41135093,  4.67022552, 11.30108029,  5.6533882 , 13.85087176],
       [13.53777389, 18.87605968,  5.79704155, 10.84715151, 13.76870507,
         8.45214742,  4.62452746,  2.47464856, 16.71150137,  8.35911514],
       [17.24376697,  6.56344818,  0.87842708, 17.18743362, 15.93665025,
         4.14188717,  7.18261782,  0.7452505 ,  3.14823319,  8.97468918],
       [ 0.31352739, 15.64479984, 14.74426791,  8.41411229, 16.62652096,
        13.63910435, 15.72764275, 10.05154323, 19.59490322, 12.5845718 ],
       [19.83790189, 16.54941647, 18.11084216,  2.87035764,  0.30018437,
         8.4861739 , 10.75019196,  9.16393109

(e) Transpose the array

In [ ]:
#Transpose of the matrix
data.T

array([[0.57941979, 0.23382876, 0.62099816, 0.67688869, 0.86218835,
        0.01567637, 0.99189509, 0.88904049],
       [0.37012872, 0.27441256, 0.31939085, 0.94380298, 0.32817241,
        0.78223999, 0.82747082, 0.31599528],
       [0.1487552 , 0.95484165, 0.71113366, 0.28985208, 0.04392135,
        0.7372134 , 0.90554211, 0.98693474],
       [0.85850761, 0.14495023, 0.86315745, 0.54235758, 0.85937168,
        0.42070561, 0.14351788, 0.9026312 ],
       [0.45700639, 0.04501631, 0.16269482, 0.68843525, 0.79683251,
        0.83132605, 0.01500922, 0.59872616],
       [0.63736474, 0.17308561, 0.97056755, 0.42260737, 0.20709436,
        0.68195522, 0.4243087 , 0.42730779],
       [0.01272707, 0.48651201, 0.23351128, 0.23122637, 0.35913089,
        0.78638214, 0.5375096 , 0.07490139],
       [0.80074665, 0.36106834, 0.56505401, 0.12373243, 0.03726253,
        0.50257716, 0.45819655, 0.84807401],
       [0.79472084, 0.34325504, 0.28266941, 0.83557507, 0.15741166,
        0.97974516, 0.131867

Create two lists of 10 elements each with values ranging from 1-20 in any order of your choice. Then convert those lists into a two-dimensional array of 2 rows and 10 columns. Check the data type, shape and dimension of the created array.

In [ ]:
data=[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]]
arr2d=np.array(data)

In [ ]:
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#the data type of the elements of the array
arr2d.dtype

dtype('int64')

In [ ]:
#the dimension of the array
arr2d.shape

(2, 10)

In [ ]:
#the dimension of the array
arr2d.ndim

2

Create two 2-D arrays with initial values of zeros and ones having 4 rows and 5 columns each. Check the data type, shape and dimension of the created array. Also, compare the elements of the two array and print the largest of the two.

In [ ]:
#array of zero
arr1=np.zeros((4,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#array of ones
arr2=np.ones((4,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#the data type of the elements of the array with zeros
arr1.dtype

dtype('float64')

In [ ]:
#the data type of the elements of the array with ones
arr1.dtype

dtype('float64')

In [ ]:
#the dimension of the array of ones
arr1.shape

(4, 5)

In [ ]:
#the dimension of the array of zeroes
arr2.shape

(4, 5)

In [ ]:
#the dimension of the array of zeroes
arr1.ndim

2

In [ ]:
#the dimension of the array of ones
arr2.ndim

2

In [ ]:
np.maximum(arr1,arr2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Create a 3-D array using empty function. Check the data type, shape and dimension of the created array. Also, convert the data type of the created array to int type.

In [ ]:
#creating a 3D array with empty function which may return array of zeros or garbage values

#creating 1 array of dimensions 3 rows and 2 cols

arr3d=np.empty((1,3,2))
arr3d

array([[[2.24981685e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
#the data type of 3d array
arr3d.dtype

dtype('float64')

In [ ]:
#shape of the array
arr3d.shape

(1, 3, 2)

In [ ]:
#dimensions of array
arr3d.ndim

3

In [ ]:
#converting data type
arr3d.astype(np.int64)

array([[[0, 0],
        [0, 0],
        [0, 0]]])

Create two random 3-D arrays of size 2 subarrays with 6 rows and 3 columns each and perform the following operations in an element-wise manner.


In [ ]:
#creating array 1
arr3d1=np.random.rand(2,6,3)
arr3d1

array([[[0.67049336, 0.59970521, 0.97087888],
        [0.98802727, 0.73310091, 0.89281776],
        [0.32970615, 0.82838812, 0.01875295],
        [0.40350783, 0.62271279, 0.57369011],
        [0.96962459, 0.11539884, 0.7934008 ],
        [0.89661437, 0.16692987, 0.58013688]],

       [[0.56811788, 0.51450734, 0.00108416],
        [0.23674659, 0.54795071, 0.74955452],
        [0.02496836, 0.92650808, 0.82008813],
        [0.54354569, 0.86348714, 0.50898633],
        [0.04586834, 0.61915524, 0.70522857],
        [0.31896968, 0.61258477, 0.69087382]]])

In [ ]:
#creating array 2
arr3d2=np.random.rand(2,6,3)
arr3d2

array([[[0.62894624, 0.307025  , 0.50070447],
        [0.30277279, 0.09448825, 0.4766142 ],
        [0.89180883, 0.30987425, 0.87991412],
        [0.00685676, 0.80716561, 0.03853264],
        [0.79738177, 0.32571922, 0.96037962],
        [0.21487421, 0.97372532, 0.82315154]],

       [[0.93100644, 0.43138625, 0.04838365],
        [0.05963712, 0.50938327, 0.75609065],
        [0.69164004, 0.26787605, 0.13567616],
        [0.84328061, 0.95194651, 0.49185536],
        [0.61967498, 0.06641435, 0.35421268],
        [0.04831939, 0.5898659 , 0.19521269]]])

(a) Addition of the two arrays


In [ ]:
np.add(arr3d1,arr3d2)

array([[[1.2994396 , 0.90673021, 1.47158335],
        [1.29080007, 0.82758916, 1.36943196],
        [1.22151498, 1.13826238, 0.89866707],
        [0.41036459, 1.4298784 , 0.61222275],
        [1.76700636, 0.44111806, 1.75378042],
        [1.11148857, 1.1406552 , 1.40328842]],

       [[1.49912432, 0.94589358, 0.0494678 ],
        [0.29638371, 1.05733398, 1.50564517],
        [0.7166084 , 1.19438413, 0.9557643 ],
        [1.3868263 , 1.81543365, 1.00084168],
        [0.66554332, 0.68556959, 1.05944125],
        [0.36728907, 1.20245067, 0.88608651]]])

(b) Multiplication of the two arrays


In [ ]:
np.multiply(arr3d1, arr3d2)

array([[[4.21704281e-01, 1.84124491e-01, 4.86123394e-01],
        [2.99147779e-01, 6.92694203e-02, 4.25529618e-01],
        [2.94034858e-01, 2.56696151e-01, 1.65009863e-02],
        [2.76675780e-03, 5.02632351e-01, 2.21057951e-02],
        [7.73160970e-01, 3.75876216e-02, 7.61965960e-01],
        [1.92659302e-01, 1.62543844e-01, 4.77540564e-01]],

       [[5.28921403e-01, 2.21951388e-01, 5.24555211e-05],
        [1.41188859e-02, 2.79116925e-01, 5.66731165e-01],
        [1.72691148e-02, 2.48189323e-01, 1.11266413e-01],
        [4.58361543e-01, 8.21993565e-01, 2.50347651e-01],
        [2.84234632e-02, 4.11207928e-02, 2.49800903e-01],
        [1.54124212e-02, 3.61342866e-01, 1.34867340e-01]]])


(c) Division of the two arrays


In [ ]:
np.divide(arr3d1, arr3d2)

array([[[1.06605830e+00, 1.95327810e+00, 1.93902580e+00],
        [3.26326305e+00, 7.75864656e+00, 1.87325046e+00],
        [3.69704963e-01, 2.67330412e+00, 2.13122515e-02],
        [5.88481462e+01, 7.71480818e-01, 1.48884190e+01],
        [1.21601049e+00, 3.54289334e-01, 8.26132484e-01],
        [4.17274077e+00, 1.71434252e-01, 7.04775312e-01]],

       [[6.10219064e-01, 1.19268368e+00, 2.24075317e-02],
        [3.96978543e+00, 1.07571398e+00, 9.91355362e-01],
        [3.61002174e-02, 3.45871936e+00, 6.04445249e+00],
        [6.44560874e-01, 9.07075276e-01, 1.03482929e+00],
        [7.40199984e-02, 9.32261246e+00, 1.99097494e+00],
        [6.60127662e+00, 1.03851531e+00, 3.53908243e+00]]])

(d) Subtraction of the two arrays


In [ ]:
np.subtract(arr3d1,arr3d2)

array([[[ 0.04154712,  0.29268021,  0.47017441],
        [ 0.68525448,  0.63861267,  0.41620357],
        [-0.56210268,  0.51851387, -0.86116117],
        [ 0.39665106, -0.18445283,  0.53515747],
        [ 0.17224283, -0.21032037, -0.16697882],
        [ 0.68174016, -0.80679545, -0.24301466]],

       [[-0.36288856,  0.08312109, -0.04729949],
        [ 0.17710946,  0.03856743, -0.00653613],
        [-0.66667169,  0.65863203,  0.68441197],
        [-0.29973492, -0.08845937,  0.01713097],
        [-0.57380664,  0.55274089,  0.35101589],
        [ 0.27065029,  0.02271887,  0.49566112]]])

(e) Raise to power with first array as base and second as power


In [ ]:
np.power(arr3d1, arr3d2)

array([[[0.77769886, 0.85471507, 0.98531135],
        [0.99635975, 0.97109017, 0.94739887],
        [0.37175896, 0.94332812, 0.0302308 ],
        [0.9937964 , 0.68226984, 0.97881632],
        [0.97570375, 0.49492683, 0.80070912],
        [0.9768237 , 0.17496925, 0.6387777 ]],

       [[0.59071857, 0.7507551 , 0.71869888],
        [0.91766482, 0.73607029, 0.80415523],
        [0.07790597, 0.97975998, 0.97344838],
        [0.59803926, 0.86959894, 0.71736772],
        [0.14810616, 0.96866254, 0.88364236],
        [0.94628395, 0.7489565 , 0.93035478]]])

(f) Comparing the two arrays - Less than, Less than equal to, equal to, Greater than, Greater than equal to


In [ ]:
#less
np.less(arr3d1, arr3d2)

array([[[False, False, False],
        [False, False, False],
        [ True, False,  True],
        [False,  True, False],
        [False,  True,  True],
        [False,  True,  True]],

       [[ True, False,  True],
        [False, False,  True],
        [ True, False, False],
        [ True,  True, False],
        [ True, False, False],
        [False, False, False]]])

In [ ]:
#less or equal
np.less_equal(arr3d1, arr3d2)

array([[[False, False, False],
        [False, False, False],
        [ True, False,  True],
        [False,  True, False],
        [False,  True,  True],
        [False,  True,  True]],

       [[ True, False,  True],
        [False, False,  True],
        [ True, False, False],
        [ True,  True, False],
        [ True, False, False],
        [False, False, False]]])

In [ ]:
#greater
np.greater(arr3d1, arr3d2)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [False,  True, False],
        [ True, False,  True],
        [ True, False, False],
        [ True, False, False]],

       [[False,  True, False],
        [ True,  True, False],
        [False,  True,  True],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True,  True]]])

In [ ]:
#greater or equal
np.greater_equal(arr3d1, arr3d2)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [False,  True, False],
        [ True, False,  True],
        [ True, False, False],
        [ True, False, False]],

       [[False,  True, False],
        [ True,  True, False],
        [False,  True,  True],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True,  True]]])

(g) Transpose of each array and then compare the two arrays as shown in part (f)


In [ ]:
#Finding the Transpose of the array 1
arrt1=arr3d1.T
arrt1

array([[[0.67049336, 0.56811788],
        [0.98802727, 0.23674659],
        [0.32970615, 0.02496836],
        [0.40350783, 0.54354569],
        [0.96962459, 0.04586834],
        [0.89661437, 0.31896968]],

       [[0.59970521, 0.51450734],
        [0.73310091, 0.54795071],
        [0.82838812, 0.92650808],
        [0.62271279, 0.86348714],
        [0.11539884, 0.61915524],
        [0.16692987, 0.61258477]],

       [[0.97087888, 0.00108416],
        [0.89281776, 0.74955452],
        [0.01875295, 0.82008813],
        [0.57369011, 0.50898633],
        [0.7934008 , 0.70522857],
        [0.58013688, 0.69087382]]])

In [ ]:
#Finding the Transpose of the array 2
arrt2=arr3d2.T
arrt2

array([[[0.62894624, 0.93100644],
        [0.30277279, 0.05963712],
        [0.89180883, 0.69164004],
        [0.00685676, 0.84328061],
        [0.79738177, 0.61967498],
        [0.21487421, 0.04831939]],

       [[0.307025  , 0.43138625],
        [0.09448825, 0.50938327],
        [0.30987425, 0.26787605],
        [0.80716561, 0.95194651],
        [0.32571922, 0.06641435],
        [0.97372532, 0.5898659 ]],

       [[0.50070447, 0.04838365],
        [0.4766142 , 0.75609065],
        [0.87991412, 0.13567616],
        [0.03853264, 0.49185536],
        [0.96037962, 0.35421268],
        [0.82315154, 0.19521269]]])

In [ ]:
#less
np.less(arrt1, arrt2)

array([[[False,  True],
        [False, False],
        [ True,  True],
        [False,  True],
        [False,  True],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [ True,  True],
        [ True, False],
        [ True, False]],

       [[False,  True],
        [False,  True],
        [ True, False],
        [False, False],
        [ True, False],
        [ True, False]]])

In [ ]:
#less or equal
np.less_equal(arrt1, arrt2)

array([[[False,  True],
        [False, False],
        [ True,  True],
        [False,  True],
        [False,  True],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [ True,  True],
        [ True, False],
        [ True, False]],

       [[False,  True],
        [False,  True],
        [ True, False],
        [False, False],
        [ True, False],
        [ True, False]]])

In [ ]:
#greater
np.greater(arrt1, arrt2)

array([[[ True, False],
        [ True,  True],
        [False, False],
        [ True, False],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [False, False],
        [False,  True],
        [False,  True]],

       [[ True, False],
        [ True, False],
        [False,  True],
        [ True,  True],
        [False,  True],
        [False,  True]]])

In [ ]:
#greater or equal
np.greater_equal(arrt1, arrt2)

array([[[ True, False],
        [ True,  True],
        [False, False],
        [ True, False],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [False, False],
        [False,  True],
        [False,  True]],

       [[ True, False],
        [ True, False],
        [False,  True],
        [ True,  True],
        [False,  True],
        [False,  True]]])

(h) Interchange the 1st and 3rd column of the array


In [ ]:
arr3d1[:,:,[0]],arr3d1[:,:,[2]]=arr3d1[:,:,[2]],arr3d1[:,:,[0]]

(i) Interchange the 2nd row with 5th row, and 1st row with 4th row of the array


In [ ]:
arr3d1[:,[0,1]],arr3d1[:,[3,4]]=arr3d1[:,[3,4]],arr3d1[:,[0,1]]


(j) Inner dot product of the two arrays


In [ ]:
#innerdot product of array 1 of both the 3d array
np.dot(arr3d1[0].T, arr3d2[0])

array([[1.4609946 , 1.89627724, 2.05429135],
       [1.7898986 , 1.3441787 , 1.96027819],
       [1.82648719, 2.05374734, 2.66705475]])

In [ ]:
#innerdot product of array 2 of both the 3d array
np.dot(arr3d2[1].T, arr3d2[1])

array([[2.44614957, 1.48969064, 0.82767701],
       [1.48969064, 1.77587779, 1.04925047],
       [0.82767701, 1.04925047, 0.99791838]])

(k) Swap the axis of the two arrays

In [ ]:
arr3d1.swapaxes(1,2)

array([[[0.57369011, 0.7934008 , 0.01875295, 0.97087888, 0.89281776,
         0.58013688],
        [0.62271279, 0.11539884, 0.82838812, 0.59970521, 0.73310091,
         0.16692987],
        [0.40350783, 0.96962459, 0.32970615, 0.67049336, 0.98802727,
         0.89661437]],

       [[0.50898633, 0.70522857, 0.82008813, 0.00108416, 0.74955452,
         0.69087382],
        [0.86348714, 0.61915524, 0.92650808, 0.51450734, 0.54795071,
         0.61258477],
        [0.54354569, 0.04586834, 0.02496836, 0.56811788, 0.23674659,
         0.31896968]]])

In [ ]:
arr3d2.swapaxes(1,2)

array([[[0.62894624, 0.30277279, 0.89180883, 0.00685676, 0.79738177,
         0.21487421],
        [0.307025  , 0.09448825, 0.30987425, 0.80716561, 0.32571922,
         0.97372532],
        [0.50070447, 0.4766142 , 0.87991412, 0.03853264, 0.96037962,
         0.82315154]],

       [[0.93100644, 0.05963712, 0.69164004, 0.84328061, 0.61967498,
         0.04831939],
        [0.43138625, 0.50938327, 0.26787605, 0.95194651, 0.06641435,
         0.5898659 ],
        [0.04838365, 0.75609065, 0.13567616, 0.49185536, 0.35421268,
         0.19521269]]])

Create a 2-D array of 9 rows and 9 columns with random values. Divide this array into 9 equal parts of 3 rows and 3 columns each. Fill these 9 parts with values from 1-9. Check whether the changes are done in the original array or the 9 parts. If the original array is getting changed, then create a copy of these 9 parts and then make the changes in filling the values from 1-9.

In [ ]:
ar=np.random.rand(9,9)
ar


array([[0.42759379, 0.07242099, 0.71501595, 0.25729939, 0.38916047,
        0.94008787, 0.48635773, 0.94304244, 0.95661998],
       [0.94494634, 0.50612106, 0.41518532, 0.20091829, 0.1952459 ,
        0.35346741, 0.26614666, 0.16450329, 0.93218096],
       [0.96235784, 0.62999146, 0.36797491, 0.25214111, 0.40764177,
        0.63956092, 0.68039788, 0.48015117, 0.38438437],
       [0.07576218, 0.25325736, 0.02709266, 0.10903162, 0.65770039,
        0.93416047, 0.95662278, 0.69666754, 0.36598979],
       [0.95688621, 0.98087734, 0.64633108, 0.82171067, 0.68764231,
        0.71133374, 0.05827899, 0.62578603, 0.77631672],
       [0.64579314, 0.76217321, 0.41188316, 0.19480136, 0.75468421,
        0.77050743, 0.04035646, 0.41988209, 0.34237803],
       [0.90550624, 0.59490705, 0.73259886, 0.20033864, 0.32895714,
        0.94038912, 0.01756133, 0.46154158, 0.23064571],
       [0.72775161, 0.12758227, 0.29946836, 0.34442384, 0.93675763,
        0.87620768, 0.63360141, 0.10113811, 0.92901108],


In [ ]:
ar1=ar[:1,:]
ar2=ar[1:2,:]
ar3=ar[2:3,:]
ar4=ar[3:4,:]
ar5=ar[4:5,:]
ar6=ar[5:6,:]
ar7=ar[6:7,:]
ar8=ar[7:8,:]
ar9=ar[8:9,:]

print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(ar5)
print(ar6)
print(ar7)
print(ar8)
print(ar9)

[[0.42759379 0.07242099 0.71501595 0.25729939 0.38916047 0.94008787
  0.48635773 0.94304244 0.95661998]]
[[0.94494634 0.50612106 0.41518532 0.20091829 0.1952459  0.35346741
  0.26614666 0.16450329 0.93218096]]
[[0.96235784 0.62999146 0.36797491 0.25214111 0.40764177 0.63956092
  0.68039788 0.48015117 0.38438437]]
[[0.07576218 0.25325736 0.02709266 0.10903162 0.65770039 0.93416047
  0.95662278 0.69666754 0.36598979]]
[[0.95688621 0.98087734 0.64633108 0.82171067 0.68764231 0.71133374
  0.05827899 0.62578603 0.77631672]]
[[0.64579314 0.76217321 0.41188316 0.19480136 0.75468421 0.77050743
  0.04035646 0.41988209 0.34237803]]
[[0.90550624 0.59490705 0.73259886 0.20033864 0.32895714 0.94038912
  0.01756133 0.46154158 0.23064571]]
[[0.72775161 0.12758227 0.29946836 0.34442384 0.93675763 0.87620768
  0.63360141 0.10113811 0.92901108]]
[[0.71118287 0.95104516 0.3857627  0.96126258 0.31902824 0.98774308
  0.94209963 0.92413367 0.05147996]]


In [ ]:
ar1[:]=[11,12,13,14,15,16,17,18,19]
ar2[:]=[11,12,13,14,15,16,17,18,19]
ar3[:]=[11,12,13,14,15,16,17,18,19]
ar4[:]=[11,12,13,14,15,16,17,18,19]
ar5[:]=[11,12,13,14,15,16,17,18,19]
ar6[:]=[11,12,13,14,15,16,17,18,19]
ar7[:]=[11,12,13,14,15,16,17,18,19]
ar8[:]=[11,12,13,14,15,16,17,18,19]
ar9[:]=[11,12,13,14,15,16,17,18,19]


print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(ar5)
print(ar6)
print(ar7)
print(ar8)
print(ar9)

[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]
[[11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [ ]:
#changes are done in orginal arr
ar

array([[11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.]])

 Create a 2-D array with empty function of size 7 rows and 3 columns and fill the elements of 


In [ ]:
arr2dd=np.empty((7,3))
arr2dd

array([[2.25599069e-316, 6.27463370e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.30276956e+180],
       [1.57076922e-076, 6.97397586e-076, 3.65961319e-086],
       [3.35809595e-143, 6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 2.80355690e-032],
       [3.31261707e-033, 3.91878251e+179, 3.44113880e+175],
       [5.50620356e-144, 1.50008929e+248, 2.59305228e-306]])

(a) each column with the column number

In [ ]:

for i in range(3):
  for j in range(7):
    arr2dd[j,i] = i
arr2dd

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

(b) each row with the row number


In [ ]:
for i in range(7):
  arr2dd[i]=i
arr2dd

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

(c) shuffle the order of rows using negative indexing

In [ ]:
arr2dd[[-3,-5,-7,-1,-4,-2,-6]]

array([[4., 4., 4.],
       [2., 2., 2.],
       [0., 0., 0.],
       [6., 6., 6.],
       [3., 3., 3.],
       [5., 5., 5.],
       [1., 1., 1.]])

Create a 1-D array of following shoe brand names - (Nike, Adidas, Reebok, Puma, Adidas, Nike, Reebok, Reebok). Now create a random array of 8 rows and 4 columns with only positive numbers and multiply each element by 10,000. This array determines the price of the shoes of various brands having four variants. Based on the following conditions, display the prices of the shoes.
  






In [ ]:
brands = np.array(['Nike', 'Addidas', 'Reebok', 'Puma', 'Adidas', 'Nike', 'Reebok','Reebok'])
data = np.random.randn(8,4)

In [ ]:
data[data<0]=1
data

array([[0.73331659, 2.11280258, 1.58264155, 0.23549576],
       [1.        , 1.59568561, 0.12727497, 1.        ],
       [1.        , 0.66586968, 0.00327626, 1.05948439],
       [0.08441686, 0.63892215, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.52012104, 1.        ],
       [1.57326776, 1.        , 1.        , 0.48583969],
       [1.        , 1.        , 0.00955144, 1.        ]])

In [ ]:
newdata=data*1000
newdata

array([[ 733.31659116, 2112.80258013, 1582.64155402,  235.4957585 ],
       [1000.        , 1595.68561273,  127.27496566, 1000.        ],
       [1000.        ,  665.86968468,    3.27626483, 1059.48439112],
       [  84.41686167,  638.92215344, 1000.        , 1000.        ],
       [1000.        , 1000.        , 1000.        , 1000.        ],
       [1000.        , 1000.        , 1520.12103795, 1000.        ],
       [1573.26776117, 1000.        , 1000.        ,  485.83968506],
       [1000.        , 1000.        ,    9.55143573, 1000.        ]])

(a) Price of all Adidas Shoes

In [ ]:
#price of addidas shoes
newdata[brands == 'Addidas']

array([[1000.        , 1595.68561273,  127.27496566, 1000.        ]])

(b) Price of all Reebok Shoes

In [ ]:
#price of reebok shoes
newdata[brands == 'Reebok']

array([[1000.        ,  665.86968468,    3.27626483, 1059.48439112],
       [1573.26776117, 1000.        , 1000.        ,  485.83968506],
       [1000.        , 1000.        ,    9.55143573, 1000.        ]])


(c) Price of all Puma Shoes

In [ ]:
#price of Puma shoes
newdata[brands == 'Puma']

array([[  84.41686167,  638.92215344, 1000.        , 1000.        ]])

(d) Price of all Nike Shoes

In [ ]:
#price of Nike shoes
newdata[brands == 'Nike']

array([[ 733.31659116, 2112.80258013, 1582.64155402,  235.4957585 ],
       [1000.        , 1000.        , 1520.12103795, 1000.        ]])

(e) Price of all Adidas or Puma Shoes 

In [ ]:
#Price of all Adidas or Puma Shoes
cond1 = brands=='Addidas'
cond2 = brands=='Puma'
newdata[cond1|cond2]

array([[1000.        , 1595.68561273,  127.27496566, 1000.        ],
       [  84.41686167,  638.92215344, 1000.        , 1000.        ]])

(f) Price of all Nike or Reebok Shoes

In [ ]:
#Price of all Nike or Reebok Shoe
cond1 = brands=='Nike'
cond2 = brands=='Reebok'
newdata[cond1|cond2]

array([[ 733.31659116, 2112.80258013, 1582.64155402,  235.4957585 ],
       [1000.        ,  665.86968468,    3.27626483, 1059.48439112],
       [1000.        , 1000.        , 1520.12103795, 1000.        ],
       [1573.26776117, 1000.        , 1000.        ,  485.83968506],
       [1000.        , 1000.        ,    9.55143573, 1000.        ]])


(j) Price of all the shoes which are more than 1500

In [ ]:
 #Price of all the shoes which are more than 1500
 newdata[newdata>1500]

array([2112.80258013, 1582.64155402, 1595.68561273, 1520.12103795,
       1573.26776117])


(k) Change the price of all the Reebok shoes to 5000

In [ ]:
#Change the price of all the Reebok shoes to 5000
newdata[brands == 'Reebok'] = 5000
newdata

array([[ 733.31659116, 2112.80258013, 1582.64155402,  235.4957585 ],
       [1000.        , 1595.68561273,  127.27496566, 1000.        ],
       [5000.        , 5000.        , 5000.        , 5000.        ],
       [  84.41686167,  638.92215344, 1000.        , 1000.        ],
       [1000.        , 1000.        , 1000.        , 1000.        ],
       [1000.        , 1000.        , 1520.12103795, 1000.        ],
       [5000.        , 5000.        , 5000.        , 5000.        ],
       [5000.        , 5000.        , 5000.        , 5000.        ]])

(h) Price of all shoes other than that of Reebok brand

In [ ]:
#Price of all shoes other than that of Reebok brand
newdata[brands!='Reebok']

array([[ 733.31659116, 2112.80258013, 1582.64155402,  235.4957585 ],
       [1000.        , 1595.68561273,  127.27496566, 1000.        ],
       [  84.41686167,  638.92215344, 1000.        , 1000.        ],
       [1000.        , 1000.        , 1000.        , 1000.        ],
       [1000.        , 1000.        , 1520.12103795, 1000.        ]])

(i) Price of 1st and 2nd variant of Shoes other than Nike or Puma brand.

In [ ]:
# Price of 1st and 2nd variant of Shoes other than Nike or Puma brand.

cond1 = brands=='Nike'
cond2 = brands=='puma'
newdata[cond1|cond2,0:2]

array([[ 733.31659116, 2112.80258013],
       [1000.        , 1000.        ]])

(l) Print only 3rd and 4th variant prices of the all the shoe brands

In [ ]:
#3rd and 4th variant prices of the all the shoe brands
newdata[:,2:]

array([[1582.64155402,  235.4957585 ],
       [ 127.27496566, 1000.        ],
       [5000.        , 5000.        ],
       [1000.        , 1000.        ],
       [1000.        , 1000.        ],
       [1520.12103795, 1000.        ],
       [5000.        , 5000.        ],
       [5000.        , 5000.        ]])

(m) Print only 1st and 2nd variant prices of first four brands of the shoes

In [ ]:
# 1st and 2nd variant prices of first four brands of the shoes
newdata[0:4,0:2]

array([[ 733.31659116, 2112.80258013],
       [1000.        , 1595.68561273],
       [5000.        , 5000.        ],
       [  84.41686167,  638.92215344]])

(g) Price of only 2nd and 3rd variant of all Nike or Adidas shoes 

In [ ]:
#2nd and 3rd variant of all Nike or Adidas shoes
cond1 = brands=='Nike'
cond2 = brands=='Adidas'
newdata[cond1|cond2,1:3]

array([[2112.80258013, 1582.64155402],
       [1000.        , 1000.        ],
       [1000.        , 1520.12103795]])